apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-service
  labels:
    app: tomcat-deployment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-deployment-service
  template:
    metadata:
      labels:
        app: tomcat-deployment-service
    spec:
      containers:
      - name: tomcat
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-deployment-service
spec:
  type: NodePort
  selector:
    app:  tomcat-deployment-service
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31234
      protocol: TCP

